### ISSUE TITLE
How best to update Hugo after setup?

### ISSUE THREAD

**Issue by zivbk1** [forestryio/create-static-site#28]
I have run the npx command and everything is working great.

When the next version of Hugo is released, what is the best method to update the version of Hugo in my project?

**Comment by ncphillips** [comment]
@chrisdmacrae used `hugo-bin` to run hugo.

Open up your `package.json` and update the version of `hugo-bin`.

https://www.npmjs.com/package/hugo-bin

**Comment by zivbk1** [comment]
Thank you.

On Feb 20, 2018 16:19, "NCPhillips" <notifications@github.com> wrote:

@chrisdmacrae <https://github.com/chrisdmacrae> used hugo-bin to run hugo.

Open up your package.json and update the version of hugo-bin.

https://www.npmjs.com/package/hugo-bin

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/forestryio/create-static-site/issues/28#issuecomment-367140547>,
or mute the thread

**Comment by zivbk1** [comment]
Easy enough.
