### ISSUE TITLE
dotfiles no longer installed?

### ISSUE THREAD

**Issue by dwalkr** [forestryio/create-static-site#44]
It seems like after the 0.1.2 release, dotfiles are no longer added to the project root.

After creating a new Hugo project, `yarn start` throws an error complaining that there is no PostCSS config file. After checking out the project, the following files are missing from the [template](https://github.com/forestryio/create-static-site/tree/master/packages/static-scripts/templates/hugo):

- .browserslistrc
- .eslintrc.yml
- .gitignore
- .postcssrc.js
- .stylelintrc.yml

**Comment by ncphillips** [comment]
The problem is that NPM the files were not uploaded with the NPM script. Look for a workaround now
